---
version: "3.7"
services:
    server:
        image: my-image:0.0.5
        container_name: my-server
        build:
            context: .
        command: ./docker-start.sh
        ports:
            - 8080:9191
        volumes:
            - /home/storage/static-file:/usr/app/static-file
            - /home/storage/db:/usr/app/db
