---
version: "3.7"
services:
    server:
        image: api-server-image:0.0.1
        container_name: api-server-image
        build:
            context: .
            dockerfile: Dockerfile-api-server
        command: npm run back:start
        ports:
            - 3001:3000
        restart: on-failure
        volumes:
            - /home/storage/static-file:/usr/app/static-file
            - /home/storage/db:/usr/app/db
