version: "3"
services:
    server:
        container_name: my_server
        build: .
        command: ./docker-start.sh
        ports:
            - 8080:9191
        volumes:
            - /home/storage/static-file:/usr/app/static-file
            - /home/storage/db:/usr/app/db
